### ISSUE TITLE
Easier setup

### ISSUE THREAD

**Issue by subins2000** [athul/shelby#20]
Like starship, perhaps simpler lines to add in bashrc :

```
eval `$(starship init bash)`
```

Also, in README it would be much more clear if the Usage instructions are included right after install. It's confusing for a newbie. `Enjoy` ? Can't enjoy unless it's made the default shell.

**Comment by athul** [comment]
I'll Update the readme like you said. 

> eval `$(starship init bash)`

I'll add support for this in the future once I get to clear all the backlogged work

**Comment by athul** [comment]
Okay, I researched onto this and it seems I'd have to make this a standalone CLI app with just the shell loading function

**Comment by athul** [comment]
@subins2000 ,

@ssiyad Seriyakki

**Comment by subins2000** [comment]
Thank you @ssiyad :) <3
