### ISSUE TITLE
Show file location even in git folders

### ISSUE THREAD

**Issue by subins2000** [athul/shelby#22]
Full directory location is not shown in git folders, just the folder name. Better if full location is shown.

**Comment by athul** [comment]
Actually, this is more of a feature than a bug.

**Comment by athul** [comment]
Possibly, I'll make a change to that in the near future

**Comment by subins2000** [comment]
@athul yeah, it's a feature request

**Comment by athul** [comment]
😆 I meant that, I made that as a feature.

**Comment by athul** [comment]
#17 Closes this issue with 5ca8933dee73b3670260c8c89427296870bb11fb and with 86da5ee8493574b11d44186e6db211e68e45b48b on git2 Branch
