### ISSUE TITLE
add prebuild binary for raspberry 3B+

### ISSUE THREAD

**Issue by Micha-Btz** [athul/shelby#32]
Hi there,

I want you build your prompt on my parpberry 3B+, but I don't get it, it's my first attempt to build a go project.

> ~/source/shelby [master|✔] $ sh -c "$(curl -sL https://git.io/ishelby)"
> athul/shelby crit platform linux/armv7 is not supported.  Make sure this script is up-to-date and file request at https://github.com/athul/shelby/issues/new
> 
> go get -v
> error: unknown switch `v'
> 
> go build
> error: Pfadspezifikation 'build' stimmt mit keinen git-bekannten Dateien überein.

Since the raspi is a very small device a prebuild binary where really great. :-)

Just  a question, is this compalibe with tmux ?

thanks and regads Micha

**Comment by Micha-Btz** [comment]
ok, build successfully on raspi, doesn't take als long as I thought.

**Comment by athul** [comment]
You got it working right? Go binaries are compatible with ARM so it ought to work

**Comment by athul** [comment]
@Micha-Btz maybe I could add a prebuilt binary for ARM. This would be just adding a line the goreleaser.yml

**Comment by Micha-Btz** [comment]
It seems to work well.
```
 dietpi on DietPi ~
❯ shelby 
NAME:
   shelby - The Prompt with Wings

USAGE:
   shelby [global options] command [command options] [arguments...]

VERSION:
   0.0.0

COMMANDS:
   init     Initialize the Shell
   info     Print directory info
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
 dietpi on DietPi ~
❯ shelby info
 dietpi on DietPi ~ dietpi on DietPi ~
❯

```
As you see, there is no versions info and the info parm itself seems to do nothing.

**Comment by athul** [comment]
`shelby info` just displays the current prompt. So from the given output it works fine IG. I may need to update the version stuff

**Comment by Micha-Btz** [comment]
After use shelby some days it is really fast and nice. One thing I would like,
if you change to a git repo, it could test with git remote update if a pull is needed. 
 ```
~/source/dotfiles on  master 
❯ git remote update 
Fordere an von origin
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 1), reused 0 (delta 0)
Entpacke Objekte: 100% (3/3), 411 Bytes | 205.00 KiB/s, Fertig.
Von https://codeberg.org/Micha_Btz/dotfiles
   54e8d4d..9a3d2f2  master     -> origin/master
 ~/source/dotfiles on  master ↓

```
Then see it directly, but it maybe slow down the prompt. Do you have an idea on keep it as fast as it is?

Thanks for the nice little tool.
